name: Publish to GitHub Pages

on:
  workflow_dispatch:

jobs:
  custom-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.1'

      - name: Install dependencies
        run: npm ci

      - name: Switch to "gh-pages" branch
        run: git checkout -B gh-pages

      - name: Build
        run: npm run build

      - name: Prepare static files
        run: npm run copy-files

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Automated commit from GitHub Action"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git subtree push --prefix github-pages origin gh-pages
