name: Publish to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      target-tag:
        description: 'Git tag that will be deployed'
        required: true

jobs:
  custom-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Checkout tag
        run: |
          git fetch --tags
          git checkout -b pre-release tags/${{ github.event.inputs.target-tag }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Prepare artifacts
        run: |
          npm run copy-files
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Publish artifacts to GitHub Pages"

      - name: Deploy artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin --delete pre-release
          git subtree push --prefix github-pages origin pre-release
          git push origin +refs/remotes/origin/pre-release:refs/heads/gh-pages

      - name: Clean up
        run: git push origin --delete pre-release
